version: "2"

services:
  
  mysql:
    image: mysql:5.5
    extends:
      file: common-services.yml
      service: logging
    environment:
    - MYSQL_ROOT_PASSWORD=secret
    ports:
    - 3306:3306
    volumes:
    - ${MYSQL_DATA}:/var/lib/mysql
    networks:
      kakao-net:
        aliases: [db, mysql]
    restart: "unless-stopped"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    extends:
      file: common-services.yml
      service: logging
    ports:
    - 8084:80
    networks:
      kakao-net:
    restart: "unless-stopped"

  msd:
    image: ${REGISTRY_URL}/mysqldumper
    networks:
      kakao-net:
    ports:
    - 8085:80
    restart: "unless-stopper"

networks: 
  kakao-net:
    external: true