version: "2"

services:
  
  mysql:
    image: mysql:5.5
    environment:
    - MYSQL_ROOT_PASSWORD=secret
    ports:
    - 0.0.0.0:3306:3306
    volumes:
    - ${MYSQL_DATA}:/var/lib/mysql
    networks:
      kakao-net:
        aliases: [db, mysql]
    extends:
      service: logging
    restart: "unless-stopped"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
    - 8084:80
    networks:
      kakao-net:
    extends:
      service: logging
    restart: "unless-stopped"

  logging:
    logging: 
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  networks: 
    kakao-net:
      external: true