version: "3"

services:
  
  mysql:
    image: mysql:5.5
    environment:
    - MYSQL_ROOT_PASSWORD=secret
    ports:
    - ${MYSQL_PORT}:3306
    volumes:
    - ${MYSQL_DATA}:/var/lib/mysql
    networks:
      mysql-net:
        aliases: [db, mysql]
    restart: "unless-stopped"

  msd:
    build: msd
    networks:
      mysql-net:
    ports:
    - ${MYSQLDUMPER_PORT}:80
    restart: "unless-stopped"

networks: 
  mysql-net:
    external: true