version: "2"

services:
  
  mysql:
    image: mysql:5.5
    environment:
    - MYSQL_ROOT_PASSWORD=secret
    ports:
    - 0.0.0.0:3306:3306
    volumes:
    - ${MYSQL_DATA}:/var/lib/mysql
    networks:
      default:
        aliases: [db, mysql]
    restart: "unless-stopped"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
    - 8084:80
    restart: "unless-stopped"
