version: "3"

services:
  
  mysql:
    image: mysql:5.5
    environment:
    - MYSQL_ROOT_PASSWORD=secret
    ports:
    - ${MYSQL_PORT}:3306
    volumes:
    - ./mysql:/etc/mysql/conf.d:ro
    - ${MYSQL_DATA}:/var/lib/mysql
    networks:
      mysql-net:
        aliases: [db, mysql]
    logging: 
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    restart: "unless-stopped"

  # msd:
  #   image: ${REGISTRY_URL}/mysqldumper
  #   networks:
  #     mysql-net:
  #   ports:
  #   - ${MYSQLDUMPER_PORT}:80
  #   restart: "unless-stopped"

networks: 
  mysql-net:
    external: true