version: "3"

services: 

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
    - ${PHPMYADMIN_PORT}:80
    logging: 
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    environment:
    - PMA_HOST=${MYSQL_HOST}
    restart: "unless-stopped"